### ISSUE TITLE
cannot npm start Please help

### ISSUE THREAD

**Issue by kowdykung** [instructure/pdf-annotate.js#26]
pdf-annotate.js@0.0.0 start /home/kowdy/Desktop/pdf-annotate.js
> ./scripts/web

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pdf-annotate.js@0.0.0 start: `./scripts/web`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdf-annotate.js@0.0.0 start script './scripts/web'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pdf-annotate.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/web
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pdf-annotate.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pdf-annotate.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kowdy/Desktop/pdf-annotate.js/npm-debug.log

**Comment by kowdykung** [comment]
this is the npm test error
Firefox 50.0.0 (Ubuntu 0.0.0) a11y::insertElementWithinChildren should insert within an element if needed FAILED
	'abcd<div>hello</div>efghijklmnopqrstuvwxyz' == 'abcde<div>hello</div>fghijklmnopqrstuvwxyz'
	@/home/kowdy/Desktop/pdf-annotate.js/test/a11y/insertElementWithinChildren.spec.js:102:7 <- webpack:///test/a11y/insertElementWithinChildren.spec.js:46:4
	
....
Firefox 50.0.0 (Ubuntu 0.0.0) a11y::insertElementWithinElement should insert an element at the proper point FAILED
	'abcd<div>hello</div>efghijklmnopqrstuvwxyz' == 'abcde<div>hello</div>fghijklmnopqrstuvwxyz'
	@/home/kowdy/Desktop/pdf-annotate.js/test/a11y/insertElementWithinElement.spec.js:100:7 <- webpack:///test/a11y/insertElementWithinElement.spec.js:44:4
	
Firefox 50.0.0 (Ubuntu 0.0.0) a11y::insertElementWithinElement should not insert within a nested element FAILED
	'abcd<div>hello</div>e<img>fghijklmnopqrstuvwxyz' == 'abcde<div>hello</div><img>fghijklmnopqrstuvwxyz'
	@/home/kowdy/Desktop/pdf-annotate.js/test/a11y/insertElementWithinElement.spec.js:109:7 <- webpack:///test/a11y/insertElementWithinElement.spec.js:53:4
	
......
Firefox 50.0.0 (Ubuntu 0.0.0) a11y::renderScreenReaderHints render should render highlight FAILED
	'a<div id="pdf-annotate-screenreader-12345" style="position: ; left: -10000px; top: auto; width: 1px; height: 1px; overf == 'a<div style="position: ; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;" id="pdf-annotate-screen
	@/home/kowdy/Desktop/pdf-annotate.js/test/a11y/renderScreenReaderHints.spec.js:138:9 <- webpack:///test/a11y/renderScreenReaderHints.spec.js:77:6
	
Firefox 50.0.0 (Ubuntu 0.0.0) a11y::renderScreenReaderHints render should render strikeout FAILED
	'abcd<div id="pdf-annotate-screenreader-12345" style="position: ; left: -10000px; top: auto; width: 1px; height: 1px; ov == 'abcde<div style="position: ; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;" id="pdf-annotate-sc
	@/home/kowdy/Desktop/pdf-annotate.js/test/a11y/renderScreenReaderHints.spec.js:159:9 <- webpack:///test/a11y/renderScreenReaderHints.spec.js:98:6
	
...........................................................
Firefox 50.0.0 (Ubuntu 0.0.0): Executed 121 of 121 (5 FAILED) (3.881 secs / 1.557 secs)
npm ERR! Test failed.  See above for more details.

**Comment by tatewaky** [comment]
ni @kowdykung  where you able to fix this?

**Comment by KaneMorgan** [comment]
The failing specs look like they're for the accessibility stuff which shouldn't really stop the project running.  

> Error: listen EADDRINUSE 127.0.0.1:8080

Is it as simple as you have something else running on port 8080?

**Comment by AP-Nothize** [comment]
Try to apply #57 so that you can pass --port 8081 when running scripts/web manually.
